name:                StadtLandFluss
version:             0.1.0.0
github:              "githubuser/StadtLandFluss"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/StadtLandFluss#readme>

dependencies:
- base >= 4.7 && < 5
- wreq == 0.5.2.1
- lens == 4.17
- containers == 0.5.11.0
- aeson == 1.4.1.0
- threepenny-gui == 0.8.3.0
- random == 1.1


library:
  source-dirs: src

executables:
  StadtLandFluss-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - StadtLandFluss

tests:
  StadtLandFluss-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - StadtLandFluss
    - hspec
    - QuickCheck

benchmarks:
  StadtLandFluss-benchmark:
    main: 		 Bench.hs
    source-dirs: 	 benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - StadtLandFluss
    - criterion
